FROM python:3.9
WORKDIR /

RUN pip install --no-cache-dir -U pip
RUN pip install --no-cache-dir -U torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113

COPY ./requirements.txt .
RUN pip install --no-cache-dir -U -r requirements.txt

COPY ./demo/ /app/
COPY ./saved_models/best_models/ /saved_models/best_models/
COPY ./prose/ /prose/

RUN if [[ -f /app/Procfile ]]; then \
  /render/build-scripts/create-process-types "/app/Procfile"; \
fi;

COPY --chown=1000:1000 /render /render/
COPY --chown=1000:1000 /app /app/

USER 1000:1000

WORKDIR /app

ENTRYPOINT [ "/render/setup-env" ]
CMD [ "/render/process/web" ]

# CMD ["uvicorn", "main:app"]
# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]